build:
	mpic++ -o tema2 BitTorrent.cpp -pthread -Wall

clean:
	rm -rf ./tema2


archive:
	rm -f "$(HOME)/Downloads/APD-Tema-2.zip"
	zip "$(HOME)/Downloads/APD-Tema-2.zip" BitTorrent.cpp README.md Makefile
